export const projectData = [
    {
        id: 1,
        name: "Social media",
        type: "Personal project ",
        teamSize: 1,
        position: "Full-Stack",
        backgroundImage: "/images/social-media.png",
        sourceCode: "https://github.com/LeManhBin/FrontEnd-social-media",
        demo: "https://front-end-social-media.vercel.app/",
        frontEnd: "HTML, CSS, ReactJs, Vite, JavaScript, Redux, Tailwind CSS",
        backEnd: "NodeJs, Express, Mongodb",
        description: "The project includes basic functions such as registration, JWT-based login, post management, profile management, friend requests, unfriending, and post liking.",
        note: "Due to the free platform, errors may occur. In case of any errors, please refresh the page."
    },
    {
        id: 2,
        name: "Bookory",
        type: "Graduation thesis",
        teamSize: 2,
        position: "Front End",
        backgroundImage: "/images/bookory.png",
        sourceCode: "https://github.com/LeManhBin/bookstore",
        demo: "https://bookstore-bookory.vercel.app/",
        frontEnd: "HTML, CSS/SCSS, ReactJs, JavaScript, Redux, Bootstrap, MUI,...",
        backEnd: "Java, Java Spring Boot, SQL Server",
        description: "The project is an automated C2C e-commerce platform that enables customers to register for sales. It includes several key functions such as register, login, product listing, reviews, catalog management, statistics, user management, and payment.",
        note: "Due to the free platform, errors may occur. In case of any errors, please refresh the page."
    },
    {
        id: 3,
        name: "Booking Hotel",
        type: "Personal project ",
        teamSize: 1,
        position: "Front End",
        backgroundImage: "/images/hotel.png",
        sourceCode: "https://github.com/LeManhBin/booking-hotel",
        demo: "https://booking-hotel-reactjs-project.vercel.app/",
        frontEnd: "HTML, CSS/SCSS, ReactJs, JavaScript, Redux, Bootstrap",
        backEnd: "Json Server Auth",
        description: "The hotel booking project includes key features like register, login, booking, reviews, room management, booking management, and statistics.",
        note: "Due to the free platform, errors may occur. In case of any errors, please refresh the page."
    },
    {
        id: 4,
        name: "Btech Shop",
        type: "Major assignment",
        teamSize: 5,
        position: "Team lead",
        backgroundImage: "/images/btechShop.png",
        sourceCode: "https://github.com/LeManhBin/demo_do_an",
        demo: "",
        frontEnd: "HTML, CSS, JavaScript, Bootstrap",
        backEnd: "Laravel, PHP, MySQL",
        description: "The project is a website for buying, selling, and managing smart device sales. It includes key functions like register, login, cart management, payment, favorites, product and catalog management, and statistics.",
        note: "Due to the free platform, errors may occur. In case of any errors, please refresh the page."
    },
    {
        id: 5,
        name: "Cara shop (landing page)",
        type: "Personal project",
        teamSize: 1,
        position: "Front End",
        backgroundImage: "/images/cara.png",
        sourceCode: "https://github.com/LeManhBin/CaRa-Shop",
        demo: "https://lemanhbin.github.io/CaRa-Shop/",
        frontEnd: "HTML, CSS, JavaScript",
        backEnd: "",
        description: "",
        note: ""
    },
    {
        id: 6,
        name: "Starbucks (landing page)",
        type: "Personal project",
        teamSize: 1,
        position: "Front End",
        backgroundImage: "/images/starbucks.png",
        sourceCode: "https://github.com/LeManhBin/starbucks-clone",
        demo: "https://lemanhbin.github.io/starbucks-clone/",
        frontEnd: "HTML, CSS, JavaScript",
        backEnd: "",
        description: "",
        note: ""
    },
]